#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1567093101                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.novosad.avocadohabit                                          # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/icon.png                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Avocado Habit                             # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Build new habits, keep track of the existing ones and explore useful insights with Avocado Habit

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Avocado Habit team                                
your_link                                 :                    
your_city                                 :                                 
email_address                             : 
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Free-to-use
    description                           : Avocado Habit is a free-to-use and easy-to-understand habit tracking app that helps you keep on top of your existing habits and build new routines and life-changing habits in a fun and gamified way.
    fontawesome_icon_name                 : comments-dollar
    
  - title                                 : Fun
    description                           : Leverage useful insights and learn how to best build and cultivate positive habits for a better life. Grow your avocado plant by completing habits and routines.
    fontawesome_icon_name                 : smile-beam

  - title                                 : Habit tracking, gamified
    description                           : Avocado Habit brings an element of fun and gamification to the process of building and cultivating your habits and routines. Grow your avocado plant by completing your habits and watch it thrive!
    fontawesome_icon_name                 : trophy

  - title                                 : Simple and clean
    description                           : We developed Avocado Habit with all users in mind, making the interface easy to navigate and insights easy to understand so everyone can benefit from the app
    fontawesome_icon_name                 : hand-point-up

  - title                                 : Notifications
    description                           : Set custom notifications and reminders and never miss a habit. You can choose the time and day to get notified in order to maximise efficiency. 
    fontawesome_icon_name                 : bell
  
  - title                                 : Powerful insights
    description                           : Keep track of your existing habits and learn from the powerful insights. Leverage these stats to improve your habit performance.
    fontawesome_icon_name                 : chart-bar

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#41B5AC"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#41B5AC"
feature_icons_background_color            : "#f5f7f9"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#f5f7f9"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
